name: flutter_fbi_test
description: Testing helpers for the Flutter FBI library (featureTest helper).
version: 0.1.2
homepage: https://github.com/hyxabrod/flutter_fbi
repository: https://github.com/hyxabrod/flutter_fbi
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_fbi: ^1.4.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: false
